name: Run tests

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:5.0-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build MockHttp.Net.csproj
      - name: Test
        run: dotnet test MockHttp.Net.csproj
